export const homeButton = "//div[@id='navbarExample']/ul//li/a[text()='Home ']";
export const contactButton = "//div[@id='navbarExample']/ul//li/a[text()='Contact']";
export const aboutUsButton = "//div[@id='navbarExample']/ul//li/a[text()='About us']";
export const cartButton = "//div[@id='navbarExample']/ul//li/a[text()='Cart']";
export const copyrightText = "//footer/p[text()='Copyright © Product Store']";
export const loginAppLogo = "//div[@class='app_logo']";
export const loginErrorMessage =
  "//button[@class='error-button']/parent::h3[contains(text(), 'Username and password do not match')]";
export const burgerButton = "//button[@id='react-burger-menu-btn']";
export const logoutButton = "//a[@id='logout_sidebar_link']";

export const logInButton = "//button[@data-qa='login-button']";
export const userNameInput = "//input[@data-qa='login-email']";
export const passwordInput = "//input[@data-qa='login-password']";
export const loginLabel = "//h2[text()='Login to your account']";
export const signUpName = "//input[@data-qa='signup-name']";
export const signUpEmail = "//input[@data-qa='signup-email']";
export const signUpLabel = "//div[@class='signup-form']/h2";
export const signUpButton = "//button[@data-qa='signup-button']";
export const gender = "//input[@id='id_gender1']";
export const enterAccInfoLabel = "//div[@class='login-form']/h2/b";
export const passwordSingUp = "//input[@id='password']";
export const daysSelectOption = "//select[@id='days']";
export const monthSelectOption = "//select[@id='months']";
export const yearSelectOption = "//select[@id='years']";
export const newsLetterCheckBox = "//input[@id='newsletter']";
export const optionCheckBox = "//input[@id='optin']";
export const firstName = "//input[@id='first_name']";
export const lastName = "//input[@id='last_name']";
export const company = "//input[@id='company']";
export const address = "//input[@id='address1']";
export const selectCountry = "//select[@id='country']";
export const state = "//input[@id='state']";
export const city = "//input[@id='city']";
export const zipCode = "//input[@id='zipcode']";
export const mobileNumber = "//input[@id='mobile_number']";
export const createAccountButton = "//button[@data-qa='create-account']";
export const accountCreateMessage = "//h2[@data-qa='account-created']/b";
export const continueButton = "//a[@data-qa='continue-button']";
export const loggedInUserName = '//i/following-sibling::b';
export const deleteAccount = "//a[text()=' Delete Account']";
export const accountDeletedMessage = "//h2[@data-qa='account-deleted']/b";
export const emailExistErrorMessage = "//p[text()='Email Address already exist!']";
export const productsButton = "//a[text()=' Products']";
