export const homeButton = "//div[@id='navbarExample']/ul//li/a[text()='Home ']";
export const contactButton = "//div[@id='navbarExample']/ul//li/a[text()='Contact']";
export const aboutUsButton = "//div[@id='navbarExample']/ul//li/a[text()='About us']";
export const cartButton = "//div[@id='navbarExample']/ul//li/a[text()='Cart']";
export const logInButton = "//div[@id='navbarExample']/ul//li/a[text()='Log in']";
export const signUpButton = "//div[@id='navbarExample']/ul//li/a[text()='Sign up']";
export const copyrightText = "//footer/p[text()='Copyright © Product Store']";
export const loginLabel = "//h5[@id='logInModalLabel']";
export const userNameInput = "//input[@id='loginusername']";
export const passwordInput = "//input[@id='loginpassword']";
export const loginButton = "//div[@class='modal-footer']/button[text() = 'Log in']";
export const loginUsername = "//li/a[@id='nameofuser']";
